### ISSUE TITLE
nanoflannConfig.cmake file is not installed in this recipe

### ISSUE THREAD

**Issue by allanleal** [conda-forge/nanoflann-feedstock#4]
Thanks for creating this recipe.

According to this [link](https://github.com/jlblancoc/nanoflann#17-use-in-your-project-via-cmake), `nanoflann` supports cmake command `find_package`, but the required cmake files in the `nanoflann` project are not installed in this recipe (i.e., `nanoflannConfig.cmake` is not installed in the conda environment; only the header file `nanoflann.hpp`).

**Comment by tadeu** [comment]
Hey @allanleal, indeed, since this package is very simple (a single include), the recipe was also kept simple. I agree that it can be improved to install CMake config files, but I think that this will need some `cmake` commands and some testing, and I don't know if it could continue to be a `noarch` package.

Please feel free if you want to try a PR here, you can also add yourself if you want to become a maintainer :)
